// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nppamqrifxpxvfaaaqba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wcGFtcXJpZnhweHZmYWFhcWJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5MTc2ODMsImV4cCI6MjA2OTQ5MzY4M30.eBrcEJUd6SZ0GgcNDvOamB5GJBeRhRulpocnEFd9D8U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});